- name: Copy current packer ssh key
  shell: cp /home/ubuntu/.ssh/authorized_keys /home/ubuntu/.ssh/authorized_keys.old

- name: Made a temp global file with all keys
  become: false
  local_action: 
    module: ansible.builtin.lineinfile 
    line: "{{ lookup('file', item) }}"
    path: "{{ public_all_filekeys_path }}"
    create: yes
  with_fileglob:
  - "{{ public_keys_path }}/*"

- name: Set authorized key to sudo user
  authorized_key:
    user: "{{ansible_user}}"
    key: "{{ lookup('file', public_all_filekeys_path) }}"
    state: present
    exclusive: "{{authorized_key_exclusive}}"

- name: Delete the temp global file with all keys
  become: false
  local_action: 
    module: file
    state: absent
    path: "{{ public_all_filekeys_path }}"

- name: Insert ssh key packer into authorized_keys file
  shell: cat /home/ubuntu/.ssh/authorized_keys.old >> /home/ubuntu/.ssh/authorized_keys

- name: Delete ssh key packer file
  shell: rm /home/ubuntu/.ssh/authorized_keys.old
